#ifndef _KEY_DRV_ENCODER_H_
#define _KEY_DRV_ENCODER_H_

#define A_ENCODER_PORT	JL_PORTB
#define B_ENCODER_PORT 	JL_PORTB
#define A_ENCODER_BIT   BIT(3)
#define B_ENCODER_BIT   BIT(4)

#define ENCODER_INIT()   do{A_ENCODER_PORT->DIR |= (A_ENCODER_BIT);A_ENCODER_PORT->PD &= ~(A_ENCODER_BIT);A_ENCODER_PORT->PU |= (A_ENCODER_BIT);\
                           B_ENCODER_PORT->DIR |= (B_ENCODER_BIT);B_ENCODER_PORT->PD &= ~(B_ENCODER_BIT);B_ENCODER_PORT->PU |= (B_ENCODER_BIT);}while(0)

#define A_ENCODER_IN    ((A_ENCODER_PORT->IN & A_ENCODER_BIT))
#define B_ENCODER_IN    ((B_ENCODER_PORT->IN & B_ENCODER_BIT))


#endif

